---
default_install_hook_types:
  - pre-commit
  - commit-msg
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-symlinks
      - id: fix-byte-order-marker
      - id: mixed-line-ending
  #      - id: trailing-whitespace # disabled, because it modifies multiline string literals to invalid values
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.24.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-angular"]
        args: ["--config", "./commitlint.config.js"]
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.16.0
    hooks:
      - id: pretty-format-kotlin
        args:
          - --ktlint-version=0.50.0
          - --autofix
