name: Build

on:
  push:
    branches:
      - '**'

jobs:
  build-and-test-with-mps:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        mpsversion: [ "2024.1.1", "2024.3", "2025.1.1", "2025.2.1" ]
        javaversion: [ 21 ]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Set up JDK
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.javaversion }}
      - name: Set up Gradle
        uses: gradle/gradle-build-action@ac2d340dc04d9e1113182899e983b5400c17cda1 # v3
      - name: Assemble
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew build publishToMavenLocal -PciBuild=true
      - name: Test with ${{ matrix.version }}
        run: cd build-tools-gradle-test && ./gradlew --build-cache build publishToMavenLocal -Pmps.version=${{ matrix.mpsversion }}
